# Generated by Django 4.1.7 on 2023-03-15 23:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_category_alter_project_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='media/projects/images'), blank=True, size=None),
        ),
    ]
