# Generated by Django 4.1.7 on 2023-03-16 14:30

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='features',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=None),
        ),
    ]
