# Generated by Django 4.1.7 on 2023-03-16 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_categories_imgae'),
        ('projects', '0004_alter_project_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_category', to='categories.categories'),
        ),
    ]
