# Generated by Django 4.1.7 on 2023-03-16 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
