# Generated by Django 4.1.7 on 2023-03-12 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportProject',
            new_name='ReportComment',
        ),
    ]
