# Generated by Django 4.1.7 on 2023-03-15 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='project',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='like_project', to='projects.project'),
            preserve_default=False,
        ),
    ]
