# Generated by Django 4.1.7 on 2023-03-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='imgae',
            field=models.ImageField(default=1, upload_to='projects/images'),
            preserve_default=False,
        ),
    ]
